version: "3.8"

services:
  shiny:
    build: ./app
    container_name: shiny_app
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - shiny
