CREATE DATABASE OR REPLACE DATABASE IF NOT EXISTS SDP;

USE SDP;

DROP TABLE LOG IF EXISTS;

CREATE TABLE LOG (
    APP VARCHAR(255)
   ,TMS BIGINT
   ,PID BIGINT
   ,THREAD VARCHAR(255)
   ,CLASS  VARCHAR(255)  
   ,METHOD VARCHAR(255)
   ,LINE   INTEGER
   ,MSG    CHAR(8)
   ,TYPE   CHAR(3)
   ,BLOCK  TINYINT
   ,CODE   SMALLINT
   ,DATA   VARCHAR(8191)
)