USE MT_POC;

CREATE TABLE MT_MASTER (
    ID BIGINT PRIMARY KEY,

    ENTERO INT,
    LARGO  BIGINT,
    MONEDA DECIMAL(10,2),
    FECHA  DATE,
    TMS    TIMESTAMP,
    FCHAR  CHAR(10),
    VCHAR  VARCHAR(255),
    LOGICO BOOLEAN
);
CREATE TABLE MT_SLAVE1 (
     ID        BIGINT PRIMARY KEY
    ,ID_PARENT BIGINT
    ,NOMBRE    VARCHAR(255)
    ,AP1       VARCHAR(255)
    ,AP2       VARCHAR(255)
    ,TFNO      INT
    ,NIF       CHAR(9)
    ,MAIL      VARCHAR(255)
    ,CP        INT
    ,TMS       TIMESTAMP
);

CREATE INDEX IDX_MT_SLAVE1_PARENT ON MT_SLAVE1(ID_PARENT);
CREATE TABLE MT_SLAVE2 (
     ID        BIGINT PRIMARY KEY
    ,ID_PARENT BIGINT
    ,PATH      VARCHAR(255)
    ,FICHERO   VARCHAR(255)
    ,LARGO     INT
    ,FECHA     DATETIME
    ,UUID      VARCHAR(255)
    ,TMS       TIMESTAMP
);

CREATE INDEX IDX_MT_SLAVE2_PARENT ON MT_SLAVE2(ID_PARENT);

CREATE TABLE MT_MASTER_NEW LIKE MT_MASTER;
CREATE TABLE MT_SLAVE1_NEW LIKE MT_SLAVE1;
CREATE TABLE MT_SLAVE2_NEW LIKE MT_SLAVE2;