USE SDP;

CREATE TABLE LOG (
   APP    VARCHAR(255)
  ,TMS    BIGINT(20)
  ,PID    BIGINT(20)
  ,THREAD VARCHAR(255)
  ,FILE   VARCHAR(255)
  ,CLASS  VARCHAR(255)
  ,METHOD VARCHAR(255)
  ,LINE   INT(11)
  ,MSG    CHAR(8)
  ,TYPE   CHAR(3)
  ,BLOCK  TINYINT(4)
  ,CODE   SMALLINT(6)
  ,BODY   VARCHAR(8191)
  ,UUID   VARCHAR(100)
  ,KEY ILOG_TMS (TMS),
  ,KEY ILOG_APP (APP, TMS)
  ,KEY ILOG_MSG (TMS, MSG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;