USE MT_POC;

CREATE TABLE MT_SLAVE1 (
     ID        BIGINT PRIMARY KEY
    ,ID_PARENT BIGINT
    ,NOMBRE    VARCHAR(255)
    ,AP1       VARCHAR(255)
    ,AP2       VARCHAR(255)
    ,TFNO      INT
    ,NIF       CHAR(9)
    ,MAIL      VARCHAR(255)
    ,CP        INT
    ,TMS       TIMESTAMP
);

CREATE INDEX IDX_MT_SLAVE1_PARENT ON MT_SLAVE1(ID_PARENT);
