USE MT_POC;

CREATE TABLE MT_SLAVE2 (
     ID        BIGINT PRIMARY KEY
    ,ID_PARENT BIGINT
    ,PATH      VARCHAR(255)
    ,FICHERO   VARCHAR(255)
    ,LARGO     INT
    ,FECHA     DATETIME
    ,UUID      VARCHAR(255)
    ,TMS       TIMESTAMP
);

CREATE INDEX IDX_MT_SLAVE2_PARENT ON MT_SLAVE2(ID_PARENT);
