USE SDP;
CREATE TABLE TPARG (
   APP      VARCHAR(64) DEFAULT 'DEF'
  ,BLOCK    SMALLINT      NOT NULL
  ,GRP      SMALLINT      NOT NULL
  ,SUBGRP   SMALLINT      NOT NULL
  ,NAME     VARCHAR(64)   NOT NULL
  ,VAL      VARCHAR(512)
  ,TYPE     SMALLINT      NOT NULL
  ,TTL      TINYINT UNSIGNED DEFAULT 0
  ,ID       INTEGER UNSIGNED
  ,LAST_TMS TIMESTAMP   ON INSERT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ,LAST_USR VARCHAR(64) ON INSERT CURRENT_USER ON UPDATE CURRENT_USER
  ,CONSTRAINT PARG_PK PRIMARY KEY (APP, BLOCK, GRP, SUBGRP, NAME)
);

CREATE VIEW PARG AS SELECT APP, BLOCK, GRP, SUBGRP, NAME, VAL, TYPE, TTL, ID FROM TPARG;

CREATE TABLE PARG_CONSTRAINT (
   ID       INTEGER UNSIGNED NOT NULL
  ,MINVAL   VARCHAR(255)
  ,MAXVAL   VARCHAR(255)
  ,REGEXP   VARCHAR(512)
  ,CONSTRAINT PARGCONST_PK PRIMARY KEY (ID)
);
-- Descripcion corta del parametro i18n
CREATE TABLE PARG_LABEL (
   ID       INTEGER UNSIGNED NOT NULL
  ,LANG     VARCHAR(2)
  ,DIALECT  VARCHAR(2)
  ,TXT      VARCHAR(512)
  ,CONSTRAINT PARGLABEL_PK PRIMARY KEY (ID, LANG,DIALECT)
);

-- Descripcion detallada del parametro i18n
CREATE TABLE PARG_DESC (
   ID       INTEGER UNSIGNED NOT NULL
  ,LANG     VARCHAR(2)
  ,DIALECT  VARCHAR(2)
  ,TXT      LONGTEXT
  ,CONSTRAINT PARGDESC_PK PRIMARY KEY (ID, LANG,DIALECT)
);
