USE SDP;
CREATE TABLE TPARG (
   APP      VARCHAR(64) DEFAULT 'DEF'
  ,BLOCK    SMALLINT      NOT NULL
  ,GRP      SMALLINT      NOT NULL
  ,SUBGRP   SMALLINT      NOT NULL
  ,NAME     VARCHAR(64)   NOT NULL
  ,VAL      VARCHAR(512)
  ,TYPE     SMALLINT      NOT NULL
  ,TTL      TINYINT UNSIGNED DEAULT 0
  ,LAST_TMS TIMESTAMP   ON INSERT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  ,LAST_USR VARCHAR(64) ON INSERT CURRENT_USER ON UPDATE CURRENT_USER
  ,CONSTRAINT PARG_PK PRIMARY KEY (APP, BLOCK, GRP, SUBGRP, NAME)
);

CREATE VIEW PARG AS SELECT APP, BLOCK, GRP, SUBGRP, NAME, VAL, TYPE, TTL FROM TPARG;      TINYINT UNSIGNED DEAULT 0
